### ISSUE TITLE
Stress and Taxes

### ISSUE THREAD

**Issue by Johncook2** [DREDGE-Mods/DredgeModDatabase#41]
### Your Discord Name

Johncook

### Mod name

Stress and Taxes

### Mod GUID

Johncook.StressandTaxes

### GitHub repository URL

https://github.com/Johncook2/Stress-and-Taxes

### Download file name

Source code

### Description (optional)

I started working on this mod before the Pale Reach, then sort of left it alone. I'm hoping if I publish it then I'll work on this more, and potentially get help easier as my code will be visible.

**Comment by MegaPiggy** [comment]
the repo is private :(
you need to make it public

**Comment by Johncook2** [comment]
Ah, sorry. Forgot that.

**Comment by Johncook2** [comment]
Okay the repo is public and I’m working on doing the step that I missed on the ReadMe. For some reason the build action isn’t working so I’m trying to do that manually.

**Comment by Johncook2** [comment]
W

**Comment by Johncook2** [comment]
What does it mean by "build your mod using an IDE"?

**Comment by xen-42** [comment]
If you have used your mod ever in game, that means you built. The github action is still preferred though, you probably want to just copy paste https://github.com/DREDGE-Mods/WinchModTemplate/blob/main/.github/workflows/release.yml to your project (I see you modified the file so best to start fresh) and replace "YourName" and "WinchModTemplate" with your "Johncook" and "StressandTaxes".
