### ISSUE TITLE
Submergence no unique fish

### ISSUE THREAD

**Issue by ahernda** [DREDGE-Mods/DredgeModDatabase#86]
[Winch-2024-10-30-22_56.log](https://github.com/user-attachments/files/17671934/Winch-2024-10-30-22_56.log)
[Winch-2024-10-30-23_03.log](https://github.com/user-attachments/files/17671935/Winch-2024-10-30-23_03.log)
[Winch-2024-10-30-23_23.log](https://github.com/user-attachments/files/17671936/Winch-2024-10-30-23_23.log)
[Winch-2024-10-31-10_33.log](https://github.com/user-attachments/files/17671937/Winch-2024-10-31-10_33.log)
[Winch-2024-10-31-10_34.log](https://github.com/user-attachments/files/17671938/Winch-2024-10-31-10_34.log)
[Winch-2024-10-31-12_49.log](https://github.com/user-attachments/files/17671939/Winch-2024-10-31-12_49.log)
[Winch-2024-10-31-12_51.log](https://github.com/user-attachments/files/17671940/Winch-2024-10-31-12_51.log)
[Winch-2024-11-07-21_17.log](https://github.com/user-attachments/files/17671941/Winch-2024-11-07-21_17.log)
[latest.log](https://github.com/user-attachments/files/17671942/latest.log)

Submergence is the only mod I have installed. The submarine and underwater base load. There are no unique fish. This is for Steam base game + Pale Reach + Iron Rig.
Log files 10-30 , mod installed in post-game. Started a new save file on 10-31.

**Comment by MegaPiggy** [comment]
I assume you meant to make an issue at https://github.com/twestpha/DredgeDeepSubmergence
